# Generated by Django 4.0.6 on 2022-07-26 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AssignedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoapp.items')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoapp.employee')),
            ],
        ),
    ]
